# Site settings
title: MyWorld
SEOTitle: Coder957's space
header-img: img/post-bg-desk.jpg
email: 1873551810@qq.com
description: "身体和灵魂都不能落下"
keyword: "coder957,分享"
url: "http://coder957.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/coder957/coder957.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # 是否开启侧边栏.
sidebar-about-description: "日常分享知识，拒绝拖延症"
#sidebar-avatar:/img/avatar-by.JPG           # 你的个人头像 这里你可以改成我在img文件夹中的两张备用照

# SNS settings
RSS: false
#zhihu_username:   怎么这么烦
#github_username:   coder957


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important







# Analytics settings
# Baidu Analytics
#ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
#ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
#ga_domain: auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
#friends: [
#    {
#       title: "zhihu",
#        href: "http://zhihu.com"
#    },{
#        title: "CSDN",
#        href: "http://www.CSDN.com"
#    },{
#        title: "coder957",
#       href: "https://github.com/coder957"
#    }
#]
